networks:
  default:
    name: clustering_phoenix_net

name: clustering_phoenix

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command:
      ["sh", "-c", "elixir --sname web_$(hostname) --cookie web -S mix phx.server"]
    entrypoint: ['./docker/entrypoint.sh']
    ports:
      - "4000-4003:4000"
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: 1
          memory: 300M
    ulimits:
      nofile: 65536
    volumes:
      - .:/app
