networks:
  default:
    name: clustering_phoenix_net

name: clustering-phoenix

services:
  clustering_phoenix:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command:
      elixir -S mix phx.server
    entrypoint: ['./docker/entrypoint.sh']
    ports:
      - "4000-4010:4000"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: 1
          memory: 300M
    ulimits:
      nofile: 65536
    volumes:
      - .:/app
